/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_TUGAS;

/**
 *
 * @author Lenovo
 */
import static CRUD_TUGAS.KoneksiProject.koneksidb;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class MataPelajaran extends javax.swing.JFrame {

    /**
     * Creates new form MataPelajaran
     */
    DefaultTableModel model;
    private Object CRUD;
    public MataPelajaran() {
        initComponents();
        String [] judul ={"Kode","Mata Pelajaran","Kelas","Jurusan"};
        model =new DefaultTableModel(judul,0);
        tabel.setModel(model);
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        jurusan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        mata_pelajaran = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btncari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Mata Pelajaran");

        jLabel2.setText("Kode");

        jLabel3.setText("Mata Pelajaran");

        jLabel4.setText("Kelas");

        jLabel5.setText("Jurusan");

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabel);

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsimpan)
                        .addGap(40, 40, 40)
                        .addComponent(btnubah)
                        .addGap(43, 43, 43)
                        .addComponent(btnhapus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jurusan)
                                    .addComponent(kelas)
                                    .addComponent(mata_pelajaran)
                                    .addComponent(kode))))
                        .addGap(18, 18, 18)
                        .addComponent(btncari)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mata_pelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus)
                    .addComponent(btnubah))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try {

            if(kode.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Kode belum diisi");
                kode.requestFocus();
            } else if(mata_pelajaran.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Mata Pelajaran belum diisi");
                mata_pelajaran.requestFocus();
            } else if(kelas.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Kelas belum diisi");
                kelas.requestFocus();
            } else if(jurusan.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Jurusan belum diisi");
                jurusan.requestFocus();
            } else {
                simpanMataPelajaran(kode.getText(), mata_pelajaran.getText(), kelas.getText(), jurusan.getText());
                JOptionPane.showMessageDialog(this, "data berhasil disimpan");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try {
            if (
                kode.getText().equals("") &&
                mata_pelajaran.getText().equals("") &&
                kelas.getText().equals("")&&
                jurusan.getText().equals("")

            )
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                kode.requestFocus();
            } else {
                ubahMataPelajaran(kode.getText(), mata_pelajaran.getText(), kelas.getText(), jurusan.getText());
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            if (
                kode.getText().equals("") &&
                mata_pelajaran.getText().equals("") &&
                kelas.getText().equals("")&&
                jurusan.getText().equals("")
            )
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                kode.requestFocus();
            } else {
                hapusMataPelajaran(kode.getText());
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                kode.setText(null);
                mata_pelajaran.setText(null);
                kelas.setText(null);
                jurusan.setText(null);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM mapel WHERE id = '"+kode.getText()+"'";
            var perintah = koneksidb.prepareStatement(sql);
            ResultSet data = perintah.executeQuery(sql);
            if (data.next()){
                mata_pelajaran.setText(data.getString("nama"));
                kelas.setText(data.getString("status"));
                jurusan.setText(data.getString("jurusan"));
            } else {
                mata_pelajaran.setText(null);
                kelas.setText(null);
                jurusan.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MataPelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MataPelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MataPelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MataPelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MataPelajaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jurusan;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField mata_pelajaran;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

        private void tampilkan() {
                    int row = tabel.getRowCount();
                    for(int a= 0; a<row;a++){
                        model.removeRow(0);
                    }
                    try {
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/2210010452_tri astuti lestari","root","");
                    ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM mapel");
                    while(rs.next()){
                        String data []= {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                        model.addRow(data);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(MataPelajaran.class.getName()).log(Level.SEVERE, null, ex);
                }
}

    private void simpanMataPelajaran(String tempkode, String tempmata_pelajaran, String tempkelas, String tempjurusan) {
        try{
                String sql = "INSERT INTO pelajaran (kode, mata_pelajaran, kelas, jurusan) VALUES (?,?,?,?)";
                PreparedStatement perintah = koneksidb.prepareStatement(sql);
                perintah.setString(1, tempkode);
                perintah.setString(2, tempmata_pelajaran);
                perintah.setString(3, tempkelas);
                perintah.setString(4, tempjurusan);
                perintah.executeUpdate();
                System.out.println("Data berhasil disimpan");
        } catch (Exception e) {
                System.out.println(e.getMessage()); 
            }  
    }

    private void ubahMataPelajaran(String tempkode, String tempmata_pelajaran, String tempkelas, String tempjurusan) {
        try{
                String sql = "UPDATE pelajaran set kode = ?, mata_pelajaran = ?, kelas = ?, AND jurusan = ?";
                PreparedStatement perintah = koneksidb.prepareStatement(sql);
                perintah.setString(1, tempkode);
                perintah.setString(2, tempmata_pelajaran);
                perintah.setString(3, tempkelas);
                perintah.setString(4, tempjurusan);
                perintah.executeUpdate();
                System.out.println("Data berhasil diubah");
        } catch (Exception e) {
                System.out.println(e.getMessage()); 
            }  
    }

    private void hapusMataPelajaran(String tempkode, String tempmata_pelajaran, String tempkelas, String tempjurusan) {
        try{
                String sql = "UPDATE pelajaran set kode = ?, mata_pelajaran = ?, kelas = ?, AND jurusan = ?";
                PreparedStatement perintah = koneksidb.prepareStatement(sql);
                perintah.setString(1, tempkode);
                perintah.setString(2, tempmata_pelajaran);
                perintah.setString(3, tempkelas);
                perintah.setString(4, tempjurusan);
                perintah.executeUpdate();
                System.out.println("Data berhasil diubah");
        } catch (Exception e) {
                System.out.println(e.getMessage()); 
            }  
    }

    private void hapusMataPelajaran(String tempkode) {
        try{
                String sql = "DELETE From pelajaran WHERE kode = ?";
                PreparedStatement perintah = koneksidb.prepareStatement(sql);
                perintah.setString(1, tempkode);
                perintah.executeUpdate();
                System.out.println("Data berhasil dihapus");
        } catch (Exception e) {
                System.out.println(e.getMessage()); 
            }  
    }
     
}
