/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_TUGAS;

/**
 *
 * @author Lenovo
 */
import static CRUD_TUGAS.KoneksiProject.koneksidb;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Nilai extends javax.swing.JFrame {

    /**
     * Creates new form Nilai
     */
    DefaultTableModel model;
    private Object CRUD;
    public Nilai() {
        initComponents();
        String [] judul ={"Id","Nis","Kode","Nilai","Jenis Nilai","Kelas","Semester"};
        model =new DefaultTableModel(judul,0);
        tabel.setModel(model);
        tampilkan();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kode = new javax.swing.JTextField();
        nilai = new javax.swing.JTextField();
        jenis_nilai = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nis = new javax.swing.JTextField();
        semester = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabel);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("NILAI");

        jLabel2.setText("Id");

        jLabel3.setText("Nis");

        jLabel4.setText("Kode");

        jLabel5.setText("Nilai");

        jLabel6.setText("Jenis Nilai");

        jLabel7.setText("Kelas");

        jLabel8.setText("Semester");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(btnsimpan)
                            .addComponent(jLabel8))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(semester, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(btnubah)
                                    .addGap(43, 43, 43)
                                    .addComponent(btnhapus))
                                .addComponent(jenis_nilai, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(nilai)
                                .addComponent(kode)
                                .addComponent(nis)
                                .addComponent(id)
                                .addComponent(kelas)))
                        .addGap(18, 18, 18)
                        .addComponent(btncari)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jenis_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus)
                    .addComponent(btnubah))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try {

            if(id.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Id belum diisi");
                id.requestFocus();
            } else if(nis.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Nis belum diisi");
                nis.requestFocus();
            } else if(kode.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Kode belum diisi");
                kode.requestFocus();
            } else if(nilai.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Nilai belum diisi");
                nilai.requestFocus();
            } else if(jenis_nilai.getText().equals("")){
                JOptionPane.showMessageDialog(this, "JenisiNilai belum diisi");
                jenis_nilai.requestFocus();
            } else if(kelas.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Kelas belum diisi");
                kelas.requestFocus();
            } else if(semester.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Semester belum diisi");
                semester.requestFocus();
            } else {
                simpanNilai(id.getText(), nis.getText(), kode.getText(), nilai.getText(), jenis_nilai.getText(), kelas.getText(), semester.getText());
                JOptionPane.showMessageDialog(this, "data berhasil disimpan");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try {
            if (
                id.getText().equals("") &&
                nis.getText().equals("") &&
                kode.getText().equals("")&&
                nilai.getText().equals("")&&
                jenis_nilai.getText().equals("")&&
                kelas.getText().equals("")&&
                semester.getText().equals("")

            )
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                id.requestFocus();
            } else {
                ubahNilai(id.getText(), nis.getText(), kode.getText(), nilai.getText(), jenis_nilai.getText(), kelas.getText(), semester.getText());
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            if (
                id.getText().equals("") &&
                nis.getText().equals("") &&
                kode.getText().equals("")&&
                nilai.getText().equals("")&&
                jenis_nilai.getText().equals("")&&
                kelas.getText().equals("")&&
                semester.getText().equals("")
            )
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                id.requestFocus();
            } else {
                hapusNilai(id.getText());
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                id.setText(null);
                nis.setText(null);
                kode.setText(null);
                nilai.setText(null);
                jenis_nilai.setText(null);
                kelas.setText(null);
                semester.setText(null);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM guru WHERE id = '"+id.getText()+"'";
            var perintah = koneksidb.prepareStatement(sql);
            ResultSet data = perintah.executeQuery(sql);
            if (data.next()){
                nis.setText(data.getString("nama"));
                kode.setText(data.getString("status"));
                nilai.setText(data.getString("status"));
                jenis_nilai.setText(data.getString("status"));
                kelas.setText(data.getString("status"));
                semester.setText(data.getString("status"));
            } else {
                nis.setText(null);
                kode.setText(null);
                nilai.setText(null);
                jenis_nilai.setText(null);
                kelas.setText(null);
                semester.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jenis_nilai;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField nilai;
    private javax.swing.JTextField nis;
    private javax.swing.JTextField semester;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        int row = tabel.getRowCount();
            for(int a= 0; a<row;a++){
                model.removeRow(0);
            }
            try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/2210010452_tri astuti lestari","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM nilai");
            while(rs.next()){
                String data []= {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Nilai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void simpanNilai(String tempid, String tempnis, String tempkode, String tempnilai, String tempjenis_nilai, String tempkelas, String tempsemester) {
        try {
            String sql = "INSERT INTO nilai (id, nis, kode, nilai, jenis_nilai, kelas, semester) VALUES (?,?,?,?,?)";
            PreparedStatement perintah = koneksidb.prepareStatement(sql);
            perintah.setString(1, tempid);
            perintah.setString(2, tempnis);
            perintah.setString(3, tempkode);
            perintah.setString(4, tempnilai);
            perintah.setString(5, tempjenis_nilai);
            perintah.setString(6, tempkelas);
            perintah.setString(7, tempsemester);
            perintah.executeUpdate();
            System.out.println("Data berhasil disimpan");
            } catch (Exception e) {
            System.out.println(e.getMessage());
            }    
    }

    private void ubahNilai(String tempid, String tempnis, String tempkode, String tempnilai, String tempjenis_nilai, String tempkelas, String tempsemester) {
        try {
                String sql = "UPDATE nilai SET id = ?, nis = ?, kode = ?, nilai = ?, jenis_nilai = ?, kelas = ? WHERE semester = ?";
                PreparedStatement perintah = koneksidb.prepareStatement(sql);
                perintah.setString(1, tempid);
                perintah.setString(2, tempnis);
                perintah.setString(3, tempkode);
                perintah.setString(4, tempnilai);
                perintah.setString(5, tempjenis_nilai);
                perintah.setString(6, tempkelas);
                perintah.setString(7, tempsemester);
                perintah.executeUpdate();
                System.out.println("Data berhasil diubah");
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
    }

    private void hapusNilai(String tempid) {
        try {
            String sql = "DELETE FROM nilai WHERE id = ?";
            PreparedStatement perintah = koneksidb.prepareStatement(sql);
            perintah.setString(1, tempid);
            perintah.executeUpdate();
            System.out.println("Data berhasil dihapus");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
